[package]
name = "srep"
version = "0.1.0"
edition = "2021"
authors = ["FlareFlo"]
license = "Apache-2.0"

[lib]
name = "srep"
path = "src/lib.rs"


[[bin]]
name = "srep"
path = "src/main.rs"

[dependencies]
prost = { version = "0.13.2", features = ["derive"] }
